apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyfuse-cloud-api
  namespace: pyfuse-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyfuse-cloud-api
  template:
    metadata:
      labels:
        app: pyfuse-cloud-api
    spec:
      containers:
        - name: api
          image: pyfuse-cloud-api:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: PYFUSE_CLOUD_MONGODB_URI
              value: mongodb://pyfuse-cloud-mongodb.pyfuse-cloud.svc.cluster.local:27017
            - name: PYFUSE_CLOUD_INTERNAL_BROKER_URL
              value: http://pyfuse-cloud-api.pyfuse-cloud.svc.cluster.local:8000/api/v1/broker
            - name: PYFUSE_CLOUD_PUBLIC_BROKER_URL
              value: http://localhost:8000/api/v1/broker
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pyfuse-cloud-api
  namespace: pyfuse-cloud
spec:
  selector:
    app: pyfuse-cloud-api
  ports:
    - port: 8000
      targetPort: 8000
