apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyfuse-cloud-frontend
  namespace: pyfuse-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyfuse-cloud-frontend
  template:
    metadata:
      labels:
        app: pyfuse-cloud-frontend
    spec:
      containers:
        - name: frontend
          image: pyfuse-cloud-frontend:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: pyfuse-cloud-frontend
  namespace: pyfuse-cloud
spec:
  selector:
    app: pyfuse-cloud-frontend
  ports:
    - port: 5173
      targetPort: 5173
