apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pyfuse-cloud-default-deny
  namespace: pyfuse-cloud
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pyfuse-cloud-allow-api-and-db
  namespace: pyfuse-cloud
spec:
  podSelector:
    matchLabels:
      app: pyfuse-cloud-worker
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: pyfuse-cloud-api
      ports:
        - protocol: TCP
          port: 8000
